version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT_INTERNAL://kafka:29092
    ports:
      - 8081:8081
  postgres-order:
    image: postgres:15
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orderdb
    ports:
      - 5443:5432
  postgres-payment:
    image: postgres:15
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: paymentdb
    ports:
      - 5444:5432
  postgres-stock:
    image: postgres:15
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: stockdb
    ports:
      - 5445:5432
